version: '2.0'
services:
    WebServer:
        build:
            context: .
            dockerfile: ./WebServer/Dockerfile
        image: webserver:latest
        container_name: webserver
        environment:
            ConnectionStrings__UserManagement: Server=dbserver;Database=UserManagementDemo;Uid=useradmin;Pwd=changeme2;
            ConnectionStrings__EventStore: "tcp://admin:changeit@eventstore:1113"
            ASPNETCORE_ENVIRONMENT: Development
        ports:
        - "8000:80"
        links:
        - EventStore
        - DbServer
    EventStore:
        image: eventstore/eventstore:5.0.8-xenial
        environment:
        - EVENTSTORE_CLUSTER_SIZE=1
        - EVENTSTORE_INT_TCP_PORT=1112
        - EVENTSTORE_EXT_TCP_PORT=1113
        - EVENTSTORE_INT_HTTP_PORT=2112
        - EVENTSTORE_EXT_HTTP_PORT=2113
        ports:
        - "1112:1112"
        - "1113:1113"
        - "2112:2112"
        - "2113:2113"
    DbServer:
        build:
            context: Database
            #dockerfile: Database/Dockerfile
        image: dbserver:latest
        container_name: dbserver
        environment:
            MYSQL_ROOT_PASSWORD: changeme
            MYSQL_DATABASE: UserManagementDemo
            MYSQL_USER: useradmin
            MYSQL_PASSWORD: changeme2
        ports:
        - "3306:3306"